# Generated by Django 3.2.21 on 2023-12-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20231219_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default='Practical internship', on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internship.type'),
        ),
    ]
