# Generated by Django 3.2.21 on 2023-12-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_alter_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='typee',
        ),
    ]
