# Generated by Django 3.2.21 on 2023-12-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_rename_type_item_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='typee',
        ),
    ]
