# Generated by Django 3.2.21 on 2023-12-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_item_typee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
