# Generated by Django 3.2.21 on 2023-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='typee',
            field=models.CharField(choices=[('practical', 'practical'), ('theoretical', 'theoretical')], default='practical', max_length=11),
        ),
    ]
