# Generated by Django 3.2.21 on 2023-12-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_auto_20231220_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
