# Generated by Django 3.2.21 on 2023-12-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_delete_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='typee',
            new_name='type_is',
        ),
    ]
