# Generated by Django 3.2.21 on 2023-12-21 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0016_auto_20231220_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to=request.models.upload_resume)),
                ('on_hold', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='internship.item')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
