# Generated by Django 3.2.21 on 2023-12-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_newrequestmodel_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequestmodel',
            name='resume',
            field=models.FileField(upload_to=None),
        ),
    ]
